import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './index.css';
import Footer from '@/components/Footer';
import Head from 'next/head';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Checkout',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" href="/icon?<generated>" type="image/<generated>" sizes="<generated>" />
      </Head>
      <body className={inter.className}>
        <div className="wrapper">
          <main className="main">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
